### ISSUE TITLE
Gradle 7.1 deprecation warnings

### ISSUE THREAD

**Issue by boris-petrov** [spring-io/nohttp#49]
Running `nohttp` on Gradle 7.1 leads to:

```
The JavaExec.main property has been deprecated. This is scheduled to be removed in Gradle 8.0. Please use the mainClass property instead. See https://docs.gradle.org/7.1/dsl/org.gradle.api.tasks.JavaExec.html#org.gradle.api.tasks.JavaExec:main for more details.
        at org.gradle.api.tasks.JavaExec.setMain(JavaExec.java:418)
        at org.gradle.api.tasks.JavaExec_Decorated.setMain(Unknown Source)
        at io.spring.nohttp.gradle.NoHttpCliPlugin.apply(NoHttpCliPlugin.java:31)
        at io.spring.nohttp.gradle.NoHttpCliPlugin.apply(NoHttpCliPlugin.java:15)
        ...
```

**Comment by boris-petrov** [comment]
There is also another one:

```
The Report.destination property has been deprecated. This is scheduled to be removed in Gradle 8.0. Please use the outputLocation property instead. See https://docs.gradle.org/7.1/dsl/org.gradle.api.reporting.Report.html#org.gradle.api.reporting.Report:destination for more details.
        at org.gradle.api.reporting.internal.SimpleReport.getDestination(SimpleReport.java:66)
        at org.gradle.api.reporting.internal.CustomizableHtmlReportImpl_Decorated.getDestination(Unknown Source)
        at io.spring.nohttp.gradle.NoHttpCheckstylePlugin$3.execute(NoHttpCheckstylePlugin.java:166)
        at io.spring.nohttp.gradle.NoHttpCheckstylePlugin$3.execute(NoHttpCheckstylePlugin.java:163)
        ...
```

**Comment by rwinch** [comment]
Thanks for the report @boris-petrov! Any chance you would be interested in submitting a PR?
